project:
  type: website
  output-dir: docs

website:
  title: "Tanner Houston"
  reader-mode: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: lux
      dark: superhero
    css: styles.css
    toc: true
    page-layout: full

editor: visual

