---
title: "About"
---

Tanner Houston is a doctoral student in Health Policy Management at Harvard Business School. He received his B.S. in Exercise Science - Pre Medicine at the University of Texas Arlington, while a member of the varsity baseball team. He then went on to receive his MBA with a concentration in Healthcare Management from Baylor University.

Prior to joining the Health Policy PhD program, he was an operations manager within HCA's Physician Service Group overseeing outpatient operations for multiple specialties including orthopedics, cardiology, and abdominal transplant surgey.

His current research interest are in organizational learning, innovation of healthcare delivery, physician decision making, and measuring the performance of healthcare delivery systems.

Outside of academia, he enjoys any and all sports, but on any given weekend you can find him watching every second of Formula 1 coverage (proud member of #TeamLH44) or playing disk golf. Some of his favorite books are *Hyperion* by Dan Simmons and *The Gunslinger* by Stephen King.

Originally from Mansfield, TX he moved to the Boston area with his wife and 5 pets (2 dogs, 2 cats, and a tortoise).
