---
title: "Comparing Cost & Utilization of Provider Types for Back and Neck Pain"
authors:
  - name: Forest Kim
    affiliation: Baylor University
  - name: David Kahle
    affiliation: Baylor University
  - name: Neil Fleming
    affiliation: Baylor University
  - name: Michael Gallaugher
    affiliation: Baylor University    
  - name: Tanner Houston
    affiliation: Harvard Business School
  - name: Sonish Lamsal
    affiliation: Baylor University
  - name: Rodney Sturdivant
    affiliation: Baylor University
date: 2025-9-11
categories: ["Published"]
citation:
  type: article-journal
  container-title: Journal of Manipulative and Physiological Therapeutics
  publisher: Elsevier
  volume: Online
links:
  - icon: globe
    text: "DOI"
    href: "https://doi.org/10.1016/j.jmpt.2024.09.013"
---

## Abstract

### Objective
The purpose of this study was to compare treatment expenditures and utilization of licensed doctors of chiropractic or doctors of physical therapy working for Airrosti (AP) compared with non-AP providers (NAP) comprising 5 different provider types.

### Methods
This study was a retrospective, claims-based, cross-sectional study using 5 years of claims and enrollment data from the state of Texas. We compared licensed doctors of chiropractic or doctors of physical therapy working for Airrosti to NAP. Episodes of care for back and neck pain were formed using 90-day clean periods. We utilized propensity scores using inverse probability weighting to control for selection bias. We examined the association of provider type with total costs per episode and 5 different measures of utilization: numbers of visits, length of episode, hospitalization, use of advanced diagnostic imaging, and use of surgery.

###Results
Included were 645 799 unique patient episodes of care. Orthopedic specialists, physiatrists, and physical therapists had higher costs and utilization than AP, except for lower visits for orthopedic specialists. Primary care providers had lower costs and utilization than AP, except for hospitalizations, in which no difference was found. AP were most similar to chiropractors in terms of costs and utilization; however, AP had higher use of advanced diagnostic imaging compared with chiropractors. Chiropractors had more visits and longer episodes than AP. Standard deviations for average episode cost, episode length, and number of visits were greater for all provider types compared with AP, except for primary care providers.

### Conclusion
In the sample studied, providers using standardized treatment pathways had reduced variation and costs for patients with spinal pain. We hypothesize that adherence to treatment pathways that align with recommended clinical practice guidelines that discourage the use of diagnostic imaging and surgery as a first step for treating lower back and neck pain may have resulted in the significant cost and utilization differences found between AP and NAP.
